export const SERVICE_REGISTRY_ABI = [
  "event ServiceRegistered(uint256 indexed id, address indexed provider, string name, uint256 pricePerJob)",
  "event ServiceUpdated(uint256 indexed id, string name, uint256 pricePerJob)",
  "event ServiceDeactivated(uint256 indexed id)",
  "function registerService(string _name, string _description, string[] _tags, uint256 _pricePerJob) returns (uint256)",
  "function updateService(uint256 _id, string _name, string _description, uint256 _pricePerJob)",
  "function deactivateService(uint256 _id)",
  "function getService(uint256 _id) view returns (uint256 id, address provider, string name, string description, string[] tags, uint256 pricePerJob, bool active, uint256 totalJobs, uint256 totalRating, uint256 ratingCount, uint256 createdAt)",
  "function findByTag(string _tag) view returns (uint256[])",
  "function getProviderServices(address _provider) view returns (uint256[])",
  "function incrementJobCount(uint256 _id)",
  "function addRating(uint256 _id, uint256 _rating)",
  "function getServiceCount() view returns (uint256)",
  "function nextServiceId() view returns (uint256)",
];

export const JOB_ESCROW_ABI = [
  "event JobCreated(uint256 indexed id, uint256 indexed serviceId, address indexed consumer, address provider, uint256 amount, string taskDescription)",
  "event ResultSubmitted(uint256 indexed id, string result)",
  "event JobCompleted(uint256 indexed id, uint256 amount)",
  "event JobCancelled(uint256 indexed id, address cancelledBy)",
  "event JobRated(uint256 indexed id, uint256 rating)",
  "function createJob(uint256 _serviceId, string _task) payable returns (uint256)",
  "function submitResult(uint256 _jobId, string _result)",
  "function confirmComplete(uint256 _jobId)",
  "function rateJob(uint256 _jobId, uint256 _rating)",
  "function cancelJob(uint256 _jobId)",
  "function claimTimeout(uint256 _jobId)",
  "function getJob(uint256 _jobId) view returns (uint256 id, uint256 serviceId, address consumer, address provider, uint256 amount, string taskDescription, string result, uint8 status, uint256 rating, uint256 createdAt, uint256 submittedAt, uint256 completedAt)",
  "function getConsumerJobs(address _consumer) view returns (uint256[])",
  "function getProviderJobs(address _provider) view returns (uint256[])",
  "function getJobCount() view returns (uint256)",
  "function nextJobId() view returns (uint256)",
  "function registry() view returns (address)",
  "function CONSUMER_CANCEL_TIMEOUT() view returns (uint256)",
  "function PROVIDER_CLAIM_TIMEOUT() view returns (uint256)",
];
